name: linc-convert
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ipython
  - typer
  - numpy
  - glymur
  - zarr
  - nibabel
  - tifffile
  - wkw
  - tensorstore
  - pytest
  - ruff
  - tifffile
  - pip
  - h5py
  - scipy
  - pip:
    - cyclopts>=3.0.0
