"""
Convert spool .dat files set generated by the LSM pipeline into a zarr.

Example input files can be found at
https://lincbrain.org/dandiset/000010/draft/files?location=sourcedata%2Frawdata
%2Fmicr%2Fsample18_run10__y10_z01_HR&page=1
"""

import logging

# externals
import cyclopts

# internals
from linc_convert.modalities.lsm.cli import lsm
from linc_convert.modalities.lsm.convert_spool import convert_spool_zarr
from linc_convert.utils.zarr_config import (
    GeneralConfig,
    NiftiConfig,
    ZarrConfig,
    autoconfig,
)

import warnings

logger = logging.getLogger(__name__)
spool = cyclopts.App(name="spool", help_format="markdown")
lsm.command(spool)


@spool.default
@autoconfig
def convert(
    inp: str,
    *,
    overlap: int = 192,
    voxel_size: list[float] = (1, 1, 1),
    general_config: GeneralConfig = None,
    zarr_config: ZarrConfig = None,
    nii_config: NiftiConfig = None,
) -> None:
    """
    Convert a collection of spool files generated by the LSM pipeline into Zarr.

    Parameters
    ----------
    inp
        Path to the root directory, which contains a collection of
        subfolders named `*_y{:02d}_z{:02d}*_HR`, each containing a
        collection of files named `*spool.dat`.
        TODO: add instrution for metadata file and info file
    overlap
        Number of pixels between slices that are overlapped
    voxel_size
        Voxel size along the X, Y and Z dimensions, in microns.
    general_config
        General configuration
    zarr_config
        Zarr related configuration
    nii_config
        NIfTI header related configuration
    """
    convert_spool_zarr(inp, overlap=overlap, voxel_size=voxel_size,
                       general_config=general_config, zarr_config=zarr_config,
                       nii_config=nii_config, use_runs=False)
    warnings.warn(
        "this is an output statement to learn if this line is run in test cases")
