"""
Convert spool .dat files set generated by the LSM pipeline into a zarr.

Example input files can be found at
https://lincbrain.org/dandiset/000010/draft/files?location=sourcedata%2Frawdata
%2Fmicr%2Fsample18_run10__y10_z01_HR&page=1
"""
import logging

# stdlib
import os
import os.path as op
import re
import warnings
from collections import defaultdict, namedtuple
from glob import glob
import dask.array as da
# externals
import cyclopts
import numpy as np

# internals
from linc_convert.modalities.lsm.cli import lsm
from linc_convert.utils.io.spool import SpoolSetInterpreter
from linc_convert.utils.io.zarr import from_config
from linc_convert.utils.nifti_header import build_nifti_header
from linc_convert.utils.zarr_config import (
    GeneralConfig,
    NiftiConfig,
    ZarrConfig,
    autoconfig,
)

logger = logging.getLogger(__name__)
stripe = cyclopts.App(name="stripe", help_format="markdown")
lsm.command(stripe)


@stripe.default
@autoconfig
def convert(
    stripe_directory: str,
    info_file:str,
    *,
    voxel_size: list[float] = (1, 1, 1),
    general_config: GeneralConfig = None,
    zarr_config: ZarrConfig = None,
    nii_config: NiftiConfig = None,
) -> None:
    """
    Convert a collection of spool files generated by the LSM pipeline into Zarr.

    Parameters
    ----------
    inp
        Path to the root directory, which contains a collection of
        subfolders named `*_y{:02d}_z{:02d}*_HR`, each containing a
        collection of files named `*spool.dat`.
        TODO: add instrution for metadata file and info file
    overlap
        Number of pixels between slices that are overlapped
    voxel_size
        Voxel size along the X, Y and Z dimensions, in microns.
    general_config
        General configuration
    zarr_config
        Zarr related configuration
    nii_config
        NIfTI header related configuration
    """

    reader = SpoolSetInterpreter(stripe_directory, info_file)


    # Set default output path if not provided
    general_config.set_default_name(op.basename(info_file))

    fullshape = reader.raw_assembled_spool_shape

    # Initialize Zarr group and array
    omz = from_config(general_config.out, zarr_config)
    array = omz.create_array("0", shape=fullshape, zarr_config=zarr_config, dtype=reader.dtype)
    logger.info(general_config.out)
    result = reader.assemble()
    result = result.transpose(1,2,0)
    array[:] = result[:]
    print("Write level 0 with shape", fullshape)


    voxel_size = list(map(float, reversed(voxel_size)))
    # Generate Zarr pyramid and metadata
    omz.generate_pyramid(levels=zarr_config.levels)
    omz.write_ome_metadata(axes=["z", "y", "x"], space_scale=voxel_size)

    if nii_config.nii:
        header = build_nifti_header(
            zgroup=omz,
            voxel_size_zyx=tuple(voxel_size),
            unit="micrometer",
            nii_config=nii_config,
        )
        omz.write_nifti_header(header)

    logger.info("Conversion complete.")

