"""
Convert spool .dat files set in one strip generated by the LSM pipeline into a zarr.

Example input files can be found at
https://lincbrain.org/dandiset/000010/draft/files?location=sourcedata%2Frawdata
%2Fmicr%2Fsample18_run10__y10_z01_HR&page=1
"""

# stdlib
import logging
import os.path as op
from typing import Optional

# externals
import cyclopts

# internals
from linc_convert.modalities.lsm.cli import lsm
from linc_convert.utils.io.spool import SpoolSetInterpreter
from linc_convert.utils.io.zarr import from_config
from linc_convert.utils.nifti_header import build_nifti_header
from linc_convert.utils.zarr_config import (
    GeneralConfig,
    NiftiConfig,
    ZarrConfig,
    autoconfig,
)

logger = logging.getLogger(__name__)
strip = cyclopts.App(name="strip", help_format="markdown")
lsm.command(strip)


@strip.default
@autoconfig
def convert(
    inp: str,
    info_file: Optional[str] = None,
    *,
    voxel_size: list[float] = (1, 1, 1),
    general_config: GeneralConfig = None,
    zarr_config: ZarrConfig = None,
    nii_config: NiftiConfig = None,
) -> None:
    """
    Convert a collection of spool files generated by the LSM pipeline into Zarr.

    Parameters
    ----------
    inp
        Path to the stripe directory, which contains a
        collection of files named `*spool.dat`.
    info_file
        Path to the info file (.mat), which contains the information
        about the scan and the spool files.
    voxel_size
        Voxel size along the X, Y and Z dimensions, in microns.
    general_config
        General configuration
    zarr_config
        Zarr related configuration
    nii_config
        NIfTI header related configuration
    """
    reader = SpoolSetInterpreter(inp, info_file)

    # Set default output path if not provided
    general_config.set_default_name(op.basename(inp))

    fullshape = reader.raw_assembled_spool_shape

    # Initialize Zarr group and array
    omz = from_config(general_config.out, zarr_config)
    array = omz.create_array(
        "0", shape=fullshape, zarr_config=zarr_config, dtype=reader.dtype
    )
    logger.info(general_config.out)
    result = reader.assemble()
    result = result.transpose(1, 2, 0)
    array[:] = result[:]
    print("Write level 0 with shape", fullshape)

    voxel_size = list(map(float, reversed(voxel_size)))
    # Generate Zarr pyramid and metadata
    omz.generate_pyramid(levels=zarr_config.levels)
    omz.write_ome_metadata(axes=["z", "y", "x"], space_scale=voxel_size)

    if nii_config.nii:
        header = build_nifti_header(
            zgroup=omz,
            voxel_size_zyx=tuple(voxel_size),
            unit="micrometer",
            nii_config=nii_config,
        )
        omz.write_nifti_header(header)

    logger.info("Conversion complete.")
